# References:
  * [https://studyopedia.com/pandas/dataframes-in-pandas/](https://studyopedia.com/pandas/dataframes-in-pandas/)

# 1- Import libraries

In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

# 1- Series


## 1.1- Question 1:
* Information:
  * N is number of integers will be generated by you

* Requirements:
  1. Generate N integers randomly (uniform distribution)
  2. Create a series (named s) from N number generated
  3. Show the results as in the output cell
    * Print series s
    * Print the index and values of s

* Guidelines:
  * To print the index: ```list(s.index)```
  * To print the values: ```list(s.values)```



In [2]:
# Declare variables
N = 15

np.random.seed(0)

# YOUR CODE IS HERE
print("Series (s): ")
s = pd.Series(np.random.randint(1, 100, N))
print(s)

Series (s): 
0     45
1     48
2     65
3     68
4     68
5     10
6     84
7     22
8     37
9     88
10    71
11    89
12    89
13    13
14    59
dtype: int64


## 1.2- Question 2:
* Information:
  * N is number of integers will be generated by you

* Requirements:
  1. Generate N integers randomly (uniform distribution), those will be the ```data``` of the series being created.
  2. Generate N integers randomly (uniform distribution), those will be the ```index``` of the series being created.
  3. Create a series (named s) from the data and the index generated
  3. Show the results as in the output cell
    * Print series s
    * Print the index and values of s

* Guidelines:
  * To print the index: ```list(s.index)```
  * To print the values: ```list(s.values)```



In [3]:
# Declare variables
N = 15

np.random.seed(0)

# YOUR CODE IS HERE
print("Series (s): ")
s = pd.Series(np.random.randint(1, 100, N), index=np.random.randint(0, 100, N))
print(s)
print("s.index: ", s.index)
print("s.values: ", s.values)

Series (s): 
65    45
39    48
87    65
46    68
88    68
81    10
37    84
25    22
77    37
72    88
9     71
20    89
80    89
69    13
79    59
dtype: int64
s.index:  Index([65, 39, 87, 46, 88, 81, 37, 25, 77, 72, 9, 20, 80, 69, 79], dtype='int64')
s.values:  [45 48 65 68 68 10 84 22 37 88 71 89 89 13 59]


## 1.3- Question 3:
* Information:
  * keys: the string contains the indices of the series being created

* Requirements:
  1. Generate N integers randomly (uniform distribution), those will be the ```data``` of the series being created; N is the length ```keys```

  2. Create a series (named s) from the data generated, and the keys is the list of characters stored in ```keys```

  3. Show the results as in the output cell
    * Print series s
    * Print the index and values of s

* Guidelines:
  * string to list: ```list(keys)```



In [4]:
keys = 'ABCDEF'
np.random.seed(0)

# YOUR CODE IS HERE

print("Series (s): ")
s = pd.Series(np.random.randint(1, 100, len(keys)), index=list(keys))
print(s)
print("s.index: ", s.index)
print("s.values: ", s.values)



Series (s): 
A    45
B    48
C    65
D    68
E    68
F    10
dtype: int64
s.index:  Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')
s.values:  [45 48 65 68 68 10]


## 1.4- Question 4:
* Information:
  * ```s```: a series of 20 items

* Requirements:
  1. Show attributes of series ```s```
  2. Call method: ```head```, ```tail``` and ```sample``` to show the first 3, the last 3 and sampled 3 items from series ```s```
  



In [5]:
np.random.seed(0)
s = pd.Series(np.random.randint(0, 100, (20, )))

# YOUR CODE IS HERE
print("s.index:  ", s.index)
print("s.values: ", s.values)
print("len(s):   ", len(s))
print("s.size:   ", s.size)
print("s.shape:  ", s.shape)
print("s.dtype:  ", s.dtype)
print("s.ndim:   ", s.ndim)
print("s.hasnans (hasnans means has Not-A-Number): ", s.hasnans)
print("-"*50)
print("s.head(3): ")
print(s.head(3))
print("s.tail(3): ")
print(s.tail(3))
print("s.sample(3): ")
print(s.sample(3))

s.index:   RangeIndex(start=0, stop=20, step=1)
s.values:  [44 47 64 67 67  9 83 21 36 87 70 88 88 12 58 65 39 87 46 88]
len(s):    20
s.size:    20
s.shape:   (20,)
s.dtype:   int64
s.ndim:    1
s.hasnans (hasnans means has Not-A-Number):  False
--------------------------------------------------
s.head(3): 
0    44
1    47
2    64
dtype: int64
s.tail(3): 
17    87
18    46
19    88
dtype: int64
s.sample(3): 
6     83
14    58
16    39
dtype: int64


## 1.5- Question 5:
* Requirements:
  1. Use method ```info()``` and ```describe()``` to show the information as in the output cell

In [6]:
pd.options.display.float_format = '{:,.1f}'.format

# YOUR CODE IS HERE

print("Information of series (s.info): ")
print(s.info())
print()
print("Description of series (s.describe): ")
print(s.describe())

Information of series (s.info): 
<class 'pandas.core.series.Series'>
RangeIndex: 20 entries, 0 to 19
Series name: None
Non-Null Count  Dtype
--------------  -----
20 non-null     int64
dtypes: int64(1)
memory usage: 288.0 bytes
None

Description of series (s.describe): 
count   20.0
mean    58.3
std     25.7
min      9.0
25%     42.8
50%     64.5
75%     84.0
max     88.0
dtype: float64


# 2- DataFrame

## 2.1- Question 1:
* Information:
  * X: numpy array 5-rows x 4-columns
  * c: list of 4 characters

* Requirements:
  1. Creat a DataFrame (named df) from data in X and columns in c
  2. Show the results as in the output cell

In [8]:
np.random.seed(0)

X = np.random.randint(0, 100, (5,4))
c = list("ABCD")
print("X: "); print(X)
print("c:", c)
print()
print("-"*100)

# YOUR CODE IS HERE
print("DataFrame (df): ")
df = pd.DataFrame(X, columns=c)
print(df)

X: 
[[44 47 64 67]
 [67  9 83 21]
 [36 87 70 88]
 [88 12 58 65]
 [39 87 46 88]]
c: ['A', 'B', 'C', 'D']

----------------------------------------------------------------------------------------------------
DataFrame (df): 
    A   B   C   D
0  44  47  64  67
1  67   9  83  21
2  36  87  70  88
3  88  12  58  65
4  39  87  46  88


## 2.2- Question 2:


In [9]:
rows = [
    {"Name": "An", "Programming": 8, "Comp-Arch": 10},
    {"Name": "Bình", "AI": 6, "Comp-Arch": 7},
    {"Name": "Tuấn", "Programming": 6.5, "DSA": 8},
    {"Name": "Nghĩa", "Discrete-Math": 9.5, "Programming": 8.5}
]
#YOUR CODE IS HERE
df = pd.DataFrame(rows)
print("DataFrame (df): ")
print(df)

DataFrame (df): 
    Name  Programming  Comp-Arch  AI  DSA  Discrete-Math
0     An          8.0       10.0 NaN  NaN            NaN
1   Bình          NaN        7.0 6.0  NaN            NaN
2   Tuấn          6.5        NaN NaN  8.0            NaN
3  Nghĩa          8.5        NaN NaN  NaN            9.5


## 2.3- Question 3:

* Requirements:
  1. Create a DataFrame (named df) from columns given in ```student```, ```rank```, and ```mark```
  2. Show the result as in the output cell

In [10]:
# Variables
student =  ["Amit", "John", "Jacob", "David", "Steve"]
rank = [1, 4, 3, 5, 2]
mark = [95, 70, 80, 60, 90]

#YOUR CODE IS HERE
print("DataFrame (df): ")
df = pd.DataFrame({"student": student, "rank": rank, "mark": mark})
print(df)

DataFrame (df): 
  student  rank  mark
0    Amit     1    95
1    John     4    70
2   Jacob     3    80
3   David     5    60
4   Steve     2    90


## 2.4- Question 4:

* Requirements:
  1. Create a DataFrame (named df) from columns given in ```rank``` and ```mark```, and use ```student``` as its its index
  2. Use ```list(df.index)``` to get list of index
  2. Show the results as in the output cell

In [11]:
# Variables
student =  ["Amit", "John", "Jacob", "David", "Steve"]
rank = [1, 4, 3, 5, 2]
mark = [95, 70, 80, 60, 90]

#YOUR CODE IS HERE
print("DataFrame (df): ")
df = pd.DataFrame({"rank": rank, "mark": mark}, index=student)
print(df)
print("index of df: ", df.index)


DataFrame (df): 
       rank  mark
Amit      1    95
John      4    70
Jacob     3    80
David     5    60
Steve     2    90
index of df:  Index(['Amit', 'John', 'Jacob', 'David', 'Steve'], dtype='object')


## 2.5- Question 5:
* Information:
  * ```df```: a DataFrame

* Requirements:
  1. Show the information of ```df``` as in the output cell
  

In [12]:
np.random.seed(0)

X = np.random.randint(0, 100, (5,4))
c = list("ABCD")
print("X: "); print(X)
print("c:", c)
print()
print("-"*100)
df = pd.DataFrame(np.random.randint(0, 100, (5,4)),
                  columns=list("ABCD"),
                  index=['row-1', 'row-2', 'row-3', 'row-4', 'row-5'])

#YOUR CODE IS HERE
print("DataFrame (df): ")
print(df)
print()
print("list(df.index): ", list(df.index))
print()
print("list(df.values):", list(df.values))
print("len(df): ", len(df))
print("df.shape: ", df.shape)
print("df.size: ", df.size)
print("type of columns (df.dtypes): ")
print(df.dtypes)
print("df.ndim: ", df.ndim)
print()
print("-"*50)
print("df.head(3): ")
print(df.head(3))
print("df.tail(3): ")
print(df.tail(3))
print("df.sample(3): ")
print(df.sample(3))


X: 
[[44 47 64 67]
 [67  9 83 21]
 [36 87 70 88]
 [88 12 58 65]
 [39 87 46 88]]
c: ['A', 'B', 'C', 'D']

----------------------------------------------------------------------------------------------------
DataFrame (df): 
        A   B   C   D
row-1  81  37  25  77
row-2  72   9  20  80
row-3  69  79  47  64
row-4  82  99  88  49
row-5  29  19  19  14

list(df.index):  ['row-1', 'row-2', 'row-3', 'row-4', 'row-5']

list(df.values): [array([81, 37, 25, 77]), array([72,  9, 20, 80]), array([69, 79, 47, 64]), array([82, 99, 88, 49]), array([29, 19, 19, 14])]
len(df):  5
df.shape:  (5, 4)
df.size:  20
type of columns (df.dtypes): 
A    int64
B    int64
C    int64
D    int64
dtype: object
df.ndim:  2

--------------------------------------------------
df.head(3): 
        A   B   C   D
row-1  81  37  25  77
row-2  72   9  20  80
row-3  69  79  47  64
df.tail(3): 
        A   B   C   D
row-3  69  79  47  64
row-4  82  99  88  49
row-5  29  19  19  14
df.sample(3): 
        A   B   C   D
row

## 2.6- Question 6:
* Requirements:
  1. Transpose DataFrame df and show the result as in the output cell
  * Guidelines:
    * use ```df.T```


In [13]:
np.random.seed(0)

X = np.random.randint(0, 100, (5,4))
c = list("ABCD")
print("X: "); print(X)
print("c:", c)
print()
print("-"*100)
df = pd.DataFrame(np.random.randint(0, 100, (5,4)),
                  columns=list("ABCD"),
                  index=['row-1', 'row-2', 'row-3', 'row-4', 'row-5'])

#YOUR CODE IS HERE

print("DataFrame df: ")
print(df)
print()
print("DataFrame df.T: ")
print(df.T)

X: 
[[44 47 64 67]
 [67  9 83 21]
 [36 87 70 88]
 [88 12 58 65]
 [39 87 46 88]]
c: ['A', 'B', 'C', 'D']

----------------------------------------------------------------------------------------------------
DataFrame df: 
        A   B   C   D
row-1  81  37  25  77
row-2  72   9  20  80
row-3  69  79  47  64
row-4  82  99  88  49
row-5  29  19  19  14

DataFrame df.T: 
   row-1  row-2  row-3  row-4  row-5
A     81     72     69     82     29
B     37      9     79     99     19
C     25     20     47     88     19
D     77     80     64     49     14


## 2.7- Question 7
* Requirements:
  1. Use method ```info()``` and ```describe()``` (transpose the result of ```describe()``` )to show the information as in the output cell

In [14]:
np.random.seed(0)

X = np.random.randint(0, 100, (5,4))
c = list("ABCD")
print("X: "); print(X)
print("c:", c)
print()
print("-"*100)
df = pd.DataFrame(np.random.randint(0, 100, (5,4)),
                  columns=list("ABCD"),
                  index=['row-1', 'row-2', 'row-3', 'row-4', 'row-5'])
pd.options.display.float_format = '{:,.1f}'.format

# YOUR CODE IS HERE
print("Information of DataFrame (df.info()): ")
print(df.info())
print()
print("Description of series (df.describe()): ")
print(df.describe())

X: 
[[44 47 64 67]
 [67  9 83 21]
 [36 87 70 88]
 [88 12 58 65]
 [39 87 46 88]]
c: ['A', 'B', 'C', 'D']

----------------------------------------------------------------------------------------------------
Information of DataFrame (df.info()): 
<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, row-1 to row-5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
 3   D       5 non-null      int64
dtypes: int64(4)
memory usage: 200.0+ bytes
None

Description of series (df.describe()): 
         A    B    C    D
count  5.0  5.0  5.0  5.0
mean  66.6 48.6 39.8 56.8
std   21.8 38.9 29.2 26.9
min   29.0  9.0 19.0 14.0
25%   69.0 19.0 20.0 49.0
50%   72.0 37.0 25.0 64.0
75%   81.0 79.0 47.0 77.0
max   82.0 99.0 88.0 80.0


# 3- Explore the information of datasets for machine learning

## 3.1- Dataset: ***sklearn.datasets.load_iris***
* References:
  * Link: [https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html)

* Information:
  * ```X```: a Dataframe, contains all samples of the dataset.
    * rows: sample/observations/data points
    * cols: features/variables/attributes
  * ```y```: a series, **contains the label for the corresponding sample, i.e., the sample has the same index in ```y```**, for examples,
    * Sample X.iloc[0] has label is y[0]
    * Sample X.iloc[1] has label is y[1]
    * and so on

* Requirements:
  * Show the information of the dataset as in the output cell.
  

In [15]:
from sklearn.datasets import load_iris

blob = load_iris(as_frame= True)
X, y = blob.data, blob.target
print("type(X): ", type(X))
print("type(y): ", type(y))

print()
print('='*100)

#YOUR CODE IS HERE

print("Dataset: IRIS")
print("-"*100)
print("Number of samples, len(x): ", len(X))
print("Number of features, X.shape[1]: ", X.shape[1])
print("Name of features, list(X.columns):")
print(list(X.columns))
print()
print("Columns's data type, X.dtypes")
print(X.dtypes)
print("Data type of label, y.dtype: ", y.dtype)
print()
print("-"*50)
print("Information of X, X.info(): ")
print(X.info())
print()
print("-"*50)
print("Description of X, X.describe().T: ")
print(X.describe().T)


type(X):  <class 'pandas.core.frame.DataFrame'>
type(y):  <class 'pandas.core.series.Series'>

Dataset: IRIS
----------------------------------------------------------------------------------------------------
Number of samples, len(x):  150
Number of features, X.shape[1]:  4
Name of features, list(X.columns):
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

Columns's data type, X.dtypes
sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
dtype: object
Data type of label, y.dtype:  int64

--------------------------------------------------
Information of X, X.info(): 
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non

## 3.2- Explore other datasets in sklearn
* References:
  * Link: [https://scikit-learn.org/stable/datasets/toy_dataset.html](https://scikit-learn.org/stable/datasets/toy_dataset.html)

  * Requirements:
    1. Do similar tasks in Question 3.1 given above to explore the other toy datasets in sklearns. Check the link given above for the name of each dataset.
    * Guidelines:
      * Create one section for each dataset
      

In [16]:
# YOUR CODE IS HERE
def explore_dataset(blob, X, y):
    print("Dataset: ", blob["DESCR"].split("\n")[0])
    print("-"*100)
    print("Number of samples, len(x): ", len(X))
    print("Number of features, X.shape[1]: ", X.shape[1])
    print("Name of features, list(X.columns):")
    print(list(X.columns))
    print()
    print("Columns's data type, X.dtypes")
    print(X.dtypes)
    print("Data type of label, y.dtype: ", y.dtype)
    print()
    print("-"*50)
    print("Information of X, X.info(): ")
    print(X.info())
    print()
    print("-"*50)
    print("Description of X, X.describe().T: ")
    print(X.describe().T)
    print()
    print("="*100)

# Load the dataset
from sklearn.datasets import load_diabetes
blob = load_diabetes(as_frame=True)
X, y = blob.data, blob.target
explore_dataset(blob, X, y)



Dataset:  .. _diabetes_dataset:
----------------------------------------------------------------------------------------------------
Number of samples, len(x):  442
Number of features, X.shape[1]:  10
Name of features, list(X.columns):
['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

Columns's data type, X.dtypes
age    float64
sex    float64
bmi    float64
bp     float64
s1     float64
s2     float64
s3     float64
s4     float64
s5     float64
s6     float64
dtype: object
Data type of label, y.dtype:  float64

--------------------------------------------------
Information of X, X.info(): 
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   age     442 non-null    float64
 1   sex     442 non-null    float64
 2   bmi     442 non-null    float64
 3   bp      442 non-null    float64
 4   s1      442 non-null    float64
 5   s2      442 non-n

# 4- Create Dataframe showing data files and their labels

## 4.1- Question 1: **BBC-NEWS**

In [17]:
# RUN THIS CELL TO DOWNLOAD THE DATASET
!rm -f bbc-fulltext.zip
!rm -rf bbc
!wget http://mlg.ucd.ie/files/datasets/bbc-fulltext.zip
!unzip -q bbc-fulltext.zip


--2024-04-05 18:20:33--  http://mlg.ucd.ie/files/datasets/bbc-fulltext.zip
Resolving mlg.ucd.ie (mlg.ucd.ie)... 137.43.93.132
Connecting to mlg.ucd.ie (mlg.ucd.ie)|137.43.93.132|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2874079 (2.7M) [application/zip]
Saving to: ‘bbc-fulltext.zip’

bbc-fulltext.zip    100%[===================>]   2.74M  4.46MB/s    in 0.6s    

2024-04-05 18:20:34 (4.46 MB/s) - ‘bbc-fulltext.zip’ saved [2874079/2874079]



### Question-1's requirements
* Information:
  * **files**: Python's list, contains all file files in the dataset
  * **labels**: Python's list, contains the label for the corresponding file in **files**, **corresponding** means **at the same index**

* Requurements:
  1. Create a DataFrame with columns are the data in ```files``` and ```labels```
  2. Show the results as in the output cell

* Guideline:
  * Use ```df.sample(10)``` to show 10 sampled randomly from the created dataframe

In [22]:
from pathlib import Path

path_to_data = './bbc'
# List all files
all_paths = Path(path_to_data).rglob('*.txt')
files = [str(path) for path in all_paths]
labels = [file.split('/')[-2] for file in files]
print("files: ", files)
print("labels:", labels)
print("="*100)

#YOUR CODE IS HERE
df = pd.DataFrame(list(zip(files, labels)), columns=['files', 'labels'])
print("DataFrame showing files and their labels:")
print("df.sample(10): ")
print("-"*50)
print(df.sample(10))
print("="*100)


files:  ['bbc/politics/343.txt', 'bbc/politics/146.txt', 'bbc/politics/314.txt', 'bbc/politics/029.txt', 'bbc/politics/199.txt', 'bbc/politics/402.txt', 'bbc/politics/021.txt', 'bbc/politics/391.txt', 'bbc/politics/155.txt', 'bbc/politics/234.txt', 'bbc/politics/206.txt', 'bbc/politics/033.txt', 'bbc/politics/067.txt', 'bbc/politics/350.txt', 'bbc/politics/405.txt', 'bbc/politics/073.txt', 'bbc/politics/278.txt', 'bbc/politics/030.txt', 'bbc/politics/075.txt', 'bbc/politics/376.txt', 'bbc/politics/152.txt', 'bbc/politics/016.txt', 'bbc/politics/365.txt', 'bbc/politics/304.txt', 'bbc/politics/283.txt', 'bbc/politics/220.txt', 'bbc/politics/276.txt', 'bbc/politics/338.txt', 'bbc/politics/415.txt', 'bbc/politics/195.txt', 'bbc/politics/245.txt', 'bbc/politics/366.txt', 'bbc/politics/006.txt', 'bbc/politics/158.txt', 'bbc/politics/062.txt', 'bbc/politics/038.txt', 'bbc/politics/040.txt', 'bbc/politics/292.txt', 'bbc/politics/001.txt', 'bbc/politics/139.txt', 'bbc/politics/239.txt', 'bbc/po

## 4.2- Question 2: **Animals10samll**
* Requirements:
  * Do similar tasks in Question-4.1 for dataset **Animals10samll**

In [26]:
%%shell
pip -q install --upgrade --no-cache-dir gdown
gdown -q 1Do8SXKm4rmXW-phHlejV-udLfhSyYgKk
echo 'download: done => file: animals10small.zip'
rm -rf ./animals10small/
unzip -q animals10small.zip
echo 'Data files in: /content/animals10small/'

download: done => file: animals10small.zip
Data files in: /content/animals10small/


In [46]:
# YOUR CODE IS HERE
import os
path_to_data = './animals10small/data'
def get_files_and_labels_then_show(path_to_data):
    all_paths = os.listdir(path_to_data)
    folders = [os.path.join(path_to_data, folder) for folder in all_paths if os.path.isdir(os.path.join(path_to_data, folder))]
    files = [os.path.join(folder, file) for folder in folders for file in os.listdir(folder)]
    labels = [file.split("/")[-2].split(".")[0] for file in files]

    print("files: ", files)
    print("labels:", labels)
    print("="*100)
    print("DataFrame showing files and their labels:")
    print("df.sample(10): ")
    print("-"*50)
    df = pd.DataFrame(list(zip(files, labels)), columns=['files', 'labels'])
    print(df.sample(10))
    print("="*100)
get_files_and_labels_then_show('./animals10small/data')

files:  ['./animals10small/data/sheep/e836b1092ef6003ed1584d05fb1d4e9fe777ead218ac104497f5c978a6eab2b0_640.jpg', './animals10small/data/sheep/e13cb60a2bf31c22d2524518b7444f92e37fe5d404b0144390f8c078a0eabd_640.jpg', './animals10small/data/sheep/ea34b6082ef7073ed1584d05fb1d4e9fe777ead218ac104497f5c978a6ebb3bf_640.jpg', './animals10small/data/sheep/ea35b30a20f2073ed1584d05fb1d4e9fe777ead218ac104497f5c978a6e8b0b1_640.jpg', './animals10small/data/sheep/e83db40e2bf1053ed1584d05fb1d4e9fe777ead218ac104497f5c978a6eab2b0_640.jpg', './animals10small/data/sheep/e830b4062ff3043ed1584d05fb1d4e9fe777ead218ac104497f5c978a6eab2b0_640.jpg', './animals10small/data/sheep/e831b30c2ef6063ed1584d05fb1d4e9fe777ead218ac104497f5c978a6ebb3bf_640.jpg', './animals10small/data/sheep/ea34b50629f0013ed1584d05fb1d4e9fe777ead218ac104497f5c978a6ebb3bf_640.jpg', './animals10small/data/sheep/e83cb90a28fc093ed1584d05fb1d4e9fe777ead218ac104497f5c978a6e8b0b1_640.jpg', './animals10small/data/sheep/e832b80721f1013ed1584d05fb1d

## 4.2- Question 3: **Flower**
* Requirements:
  * Do similar tasks in Question-4.1 for dataset **Flower**

In [43]:
!rm -f flower_photos.tgz
!wget https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz
!tar -xzf flower_photos.tgz
path_to_data = './flower_photos'

--2024-04-05 18:42:41--  https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.31.207, 142.251.111.207, 142.251.16.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.31.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 228813984 (218M) [application/x-compressed-tar]
Saving to: ‘flower_photos.tgz’

flower_photos.tgz   100%[===================>] 218.21M   125MB/s    in 1.7s    

2024-04-05 18:42:43 (125 MB/s) - ‘flower_photos.tgz’ saved [228813984/228813984]



In [44]:
# YOUR CODE IS HERE
get_files_and_labels_then_show('./flower_photos')

files:  ['./flower_photos/sunflowers/15054753070_4f6ae0e763_m.jpg', './flower_photos/sunflowers/20621698991_dcb323911d.jpg', './flower_photos/sunflowers/3575811488_a31714472a.jpg', './flower_photos/sunflowers/3815322974_52c12dbde3.jpg', './flower_photos/sunflowers/4868595281_1e58083785.jpg', './flower_photos/sunflowers/5927432662_3ffd2461c2_n.jpg', './flower_photos/sunflowers/4895720722_8247f2015b_n.jpg', './flower_photos/sunflowers/8928658373_fdca5ff1b8.jpg', './flower_photos/sunflowers/3848405800_8eea982c40.jpg', './flower_photos/sunflowers/4933229095_f7e4218b28.jpg', './flower_photos/sunflowers/4933822272_79af205b94.jpg', './flower_photos/sunflowers/200557979_a16112aac1_n.jpg', './flower_photos/sunflowers/5139977579_ea2dd6a322_m.jpg', './flower_photos/sunflowers/6198569587_23c3693328_m.jpg', './flower_photos/sunflowers/2729206569_9dd2b5a3ed.jpg', './flower_photos/sunflowers/2816256710_a2d3616fae.jpg', './flower_photos/sunflowers/19784656639_cd7f0a4a26_m.jpg', './flower_photos/sunflo

## 4.2- Question 3: **OxfordPet**
* Requirements:
  * Do similar tasks in Question-4.1 for dataset **OxfordPet**
  * **OxfordPet**: has been examplified in previous questions, about "Indexing" with Numpy

In [45]:
# Download the dataset
!rm -f images.tar.gz annotations.tar.gz
!wget https://thor.robots.ox.ac.uk/~vgg/data/pets/images.tar.gz
!wget https://thor.robots.ox.ac.uk/~vgg/data/pets/annotations.tar.gz
!tar -xzf images.tar.gz
!tar -xzf annotations.tar.gz

--2024-04-05 18:42:55--  https://thor.robots.ox.ac.uk/~vgg/data/pets/images.tar.gz
Resolving thor.robots.ox.ac.uk (thor.robots.ox.ac.uk)... 129.67.95.98
Connecting to thor.robots.ox.ac.uk (thor.robots.ox.ac.uk)|129.67.95.98|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://thor.robots.ox.ac.uk/datasets/pets/images.tar.gz [following]
--2024-04-05 18:42:55--  https://thor.robots.ox.ac.uk/datasets/pets/images.tar.gz
Reusing existing connection to thor.robots.ox.ac.uk:443.
HTTP request sent, awaiting response... 200 OK
Length: 791918971 (755M) [application/octet-stream]
Saving to: ‘images.tar.gz’

images.tar.gz       100%[===================>] 755.23M  35.8MB/s    in 22s     

2024-04-05 18:43:18 (34.3 MB/s) - ‘images.tar.gz’ saved [791918971/791918971]

--2024-04-05 18:43:18--  https://thor.robots.ox.ac.uk/~vgg/data/pets/annotations.tar.gz
Resolving thor.robots.ox.ac.uk (thor.robots.ox.ac.uk)... 129.67.95.98
Connecting to thor.robots.ox.ac.

In [62]:
# YOUR CODE IS HERE
def get_files_and_labels_then_show(path_to_data):
    all_paths = os.listdir(path_to_data)
    labels = sorted([str(os.path.join(path_to_data, 'trimaps', file)) for file in os.listdir(os.path.join(path_to_data, 'trimaps'))])
    # files = sorted([str(os.path.join(path_to_data, 'xmls', file)) for file in os.listdir(os.path.join(path_to_data, 'xmls'))])
    files = [x.replace('trimaps', 'xmls').replace('._', '').replace('.png', '.xml') for x in labels]
    print("files: ", files)
    print("labels:", labels)
    print("="*100)
    print("DataFrame showing files and their labels:")
    print("df.sample(10): ")
    print("-"*50)
    df = pd.DataFrame(list(zip(files, labels)), columns=['files', 'labels'])
    print(df.sample(10))
    print("="*100)
get_files_and_labels_then_show('./annotations/')

files:  ['./annotations/xmls/Abyssinian_1.xml', './annotations/xmls/Abyssinian_10.xml', './annotations/xmls/Abyssinian_100.xml', './annotations/xmls/Abyssinian_101.xml', './annotations/xmls/Abyssinian_102.xml', './annotations/xmls/Abyssinian_103.xml', './annotations/xmls/Abyssinian_104.xml', './annotations/xmls/Abyssinian_105.xml', './annotations/xmls/Abyssinian_106.xml', './annotations/xmls/Abyssinian_107.xml', './annotations/xmls/Abyssinian_108.xml', './annotations/xmls/Abyssinian_109.xml', './annotations/xmls/Abyssinian_11.xml', './annotations/xmls/Abyssinian_110.xml', './annotations/xmls/Abyssinian_111.xml', './annotations/xmls/Abyssinian_112.xml', './annotations/xmls/Abyssinian_113.xml', './annotations/xmls/Abyssinian_114.xml', './annotations/xmls/Abyssinian_115.xml', './annotations/xmls/Abyssinian_116.xml', './annotations/xmls/Abyssinian_117.xml', './annotations/xmls/Abyssinian_118.xml', './annotations/xmls/Abyssinian_119.xml', './annotations/xmls/Abyssinian_12.xml', './annotatio